### ISSUE TITLE
no collection listing when i click the collection tab

### ISSUE THREAD

**Issue by gjergjsheldija** [omeka/plugin-MultiCollections#1]
hi.

testing the multicollections plugin, i noticed something strange.
after installing the plugin, i cannot see my old collections anymore.
i've checked the override regular collection tab.

regards
gj.

**Comment by patrickmj** [comment]
Thanks for the feedback. Could I ask where you are looking that you expect to see your collections? On the admin side, the URL when you click the tab should be like: Omeka/admin/multi-collections/multi-collections/browse

If you are expecting to see the collections on the public side, that would call for modifications to your them files. Info about that is in the README.

Also, what version of Omeka are you running?

Thanks! The plugin isn't officially released yet, but help like this will get it there more quickly!

**Comment by gjergjsheldija** [comment]
hi,

i installed the plugin, on an omeka installation with preexisting categories.
the error i have is that when i click on the collections tab in the admin interface, 
that is .. admin/multi-collections/multi-collections/browse, it does not list the categories.
i'm using omeka 1.5.

thanks, for the great plugin

gj.

**Comment by gjergjsheldija** [comment]
hi

think i narrowed the thing a bit.
the error is generated in file ../views/admin/multicollections/browse.php line 34
the method multicollections_link_to_collection() is not defined..

regards
gj.

**Comment by gjergjsheldija** [comment]
hi,

i think i fixed it.
in file helpers/functions.php add the following function

``` php
function multicollections_link_to_collection($text=null, $props=array(), $action='show', $collectionObj = null)
{
    if (!$collectionObj) {
        $collectionObj = get_current_collection();
    }

    $collectionName = collection('name', array(), $collectionObj);

    $text = (!empty($text) ? $text : (!empty($collectionName) ? $collectionName : __('[Untitled]')));

    return link_to($collectionObj, $action, $text, $props);
}
```

regards
gj.

**Comment by patrickmj** [comment]
Ah! That does explain things! That's also my bad, since I hadn't pushed new code up to github in a while.

The most current version actually doesn't have multicollections_link_to_collection. It just uses Omeka's built in function, so line 34 of browse.php reverts back to :

``` html
<td class="title"><?php echo link_to_collection(); ?></td>
```

Thanks!

**Comment by gjergjsheldija** [comment]
now it works :) and that's good :)
could you please update also the functions.php file ?
gj.

**Comment by patrickmj** [comment]
Yep. that's done now. Thanks!
